### ISSUE TITLE
What are default pins for the screen?

### ISSUE THREAD

**Issue by HaochengZheng** [adafruit/Adafruit-ESP32-S2-TFT-Feather-PCB#1]
In the example program, it is only stated: "Adafruit_ST7789 tft = Adafruit_ST7789(TFT_CS, TFT_DC, TFT_RST);" However I need to use the board in ESP IDF where I have to change pin assignments for CS, DC, MOSI, SCLK and RST, but I cannot find their default settings. So what are they assigned to? Thanks

**Comment by ladyada** [comment]
check the schematic for absolute GPIO numbers
https://learn.adafruit.com/assets/107732
