### ISSUE TITLE
Does it work with ESP-IDF?

### ISSUE THREAD

**Issue by HaochengZheng** [adafruit/Adafruit-ESP32-S2-TFT-Feather-PCB#2]
Maybe this is a dumb question, but does this esp32-s2 feather work with ESP-IDF? I've been trying to run some code on this product but failed. Is it only compatible with Circuit Python and Arduino?

**Comment by dhalbert** [comment]
We use ESP-IDF inside CIrcuitPython and Arduino, so certainly! But there may not be a specific board definition for it? Please ask for further help in discord, https://adafru.it/discord, or in the forums: https://forums.adafruit.com.
